service: serverless-wso2-apim
provider:
  name: aws
plugins:
  localPath: '../../../../../'
  modules:
    - src

############################################################################
# -- START HERE : Modify the plugin configuration to suit the test case -- #
custom:
  wso2apim:
    enabled: true
    host: ${env:WSO2_HOST}
    port: ${env:WSO2_PORT}
    versionSlug: 'v0.14'
    user: ${env:WSO2_USER}
    pass: ${env:WSO2_PASS}
    gatewayEnv: ${env:WSO2_ENV}
    apidefs:
      - name: ${env:TEST_ID}-1
        description: ${env:TEST_ID}-1
        rootContext: /${env:TEST_ID}-1
        version: 'v1'
        visibility: 'PUBLIC'
        backend:
          http:
            baseUrl: 'https://baseUrl'
        maxTps: 10
        tags:
          - ${env:TEST_ID}-1
        swaggerSpec:
          swagger: '2.0'
          info:
            title: ${env:TEST_ID}-1
            version: 'v1'
            contact:
              name: ${env:TEST_ID}-1
              email: ${env:TEST_ID}-1
          paths:
            /*:
              post:
                responses:
                  '201':
                    description: Created
                x-auth-type: 'None'
      - name: ${env:TEST_ID}-2
        description: ${env:TEST_ID}-2
        rootContext: /${env:TEST_ID}-2
        version: 'v1'
        visibility: 'PUBLIC'
        backend:
          http:
            baseUrl: 'https://baseUrl'
        maxTps: 10
        tags:
          - ${env:TEST_ID}-2
        swaggerSpec:
          openapi: 3.0.0
          info:
            title: ${env:TEST_ID}-2
            version: "v1"
            contact:
              name: ${env:TEST_ID}-2
              email: ${env:TEST_ID}-2
          paths:
            /*:
              post:
                responses:
                  "201":
                    description: Created
                x-auth-type: 'None'